#!/usr/bin/env bash
# Shared configuration for the local Goji integration stack.
# Source this, do not execute it:  source scripts/local-env.sh
#
# The keys below are the fixed Supabase *local development* demo keys. They are
# identical on every `supabase start` machine and are not secrets. The live
# family project's keys never appear in this repo (CLAUDE.md rule 4).

GOJI_DOCS_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export GOJI_DOCS_ROOT
export GOJI_COMPUTER_DIR="$GOJI_DOCS_ROOT/goji_computer"
export GOJI_CLOUD_DIR="$GOJI_DOCS_ROOT/goji_cloud"
export GOJI_APP_DIR="$GOJI_DOCS_ROOT/goji_learner_app"

# --- Local cloud (goji_cloud `supabase start`) -------------------------------
export SB_URL="http://127.0.0.1:54321"
export SB_DB_PORT="54322"
export SB_DB_CONTAINER="supabase_db_cloud"
export SB_ANON="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"
export SB_SERVICE="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU"

# Services the CLI can skip locally: Studio/imgproxy/vector/logflare/supavisor
# are developer conveniences, not part of the sync contract. Realtime is kept
# because `supabase start` runs its migrations as part of schema init.
export SB_EXCLUDE="studio,imgproxy,vector,logflare,supavisor"

# --- Device (goji_computer) --------------------------------------------------
export GOJI_BACKEND_URL="http://127.0.0.1:5000"
export GOJI_KIOSK_URL="http://127.0.0.1:5173"

# --- Parent app (goji_learner_app, built for web) ---------------------------
export GOJI_PARENT_APP_URL="http://127.0.0.1:8088"
export GOJI_PARENT_APP_PORT="8088"

# --- Demo parent account on the local cloud ---------------------------------
export GOJI_TEST_EMAIL="parent@goji.test"
export GOJI_TEST_PASSWORD="gojitest123"

# tmux session names (one per long-running service)
export TMUX_CONF="/exec-daemon/tmux.portal.conf"
export SESS_BACKEND="goji-backend"
export SESS_KIOSK="goji-frontend"
export SESS_APP="goji-parent-app"
export SESS_SYNC="goji-sync-agent"

# tmux helper that tolerates a missing portal config (local machines).
goji_tmux() {
  if [ -f "$TMUX_CONF" ]; then
    tmux -f "$TMUX_CONF" "$@"
  else
    tmux "$@"
  fi
}

# Start (or restart) a named service in its own tmux session.
goji_service() {
  local name="$1" dir="$2" cmd="$3"
  goji_tmux kill-session -t "=$name" 2>/dev/null || true
  goji_tmux new-session -d -s "$name" -c "$dir" -- bash -l
  goji_tmux send-keys -t "$name:0.0" "cd '$dir' && $cmd" C-m
}

# Poll a URL until it answers, so callers never race a booting service.
goji_wait_http() {
  local url="$1" label="$2" tries="${3:-60}"
  local i
  for ((i = 0; i < tries; i++)); do
    if curl -fsS -o /dev/null --max-time 3 "$url" 2>/dev/null; then
      echo "  ready: $label ($url)"
      return 0
    fi
    sleep 2
  done
  echo "  TIMEOUT waiting for $label ($url)" >&2
  return 1
}

# Write the device's live-cloud env file.
#
# Generated rather than committed: goji_computer is the flashable SD image
# source (CLAUDE.md rule 3), so local dev-cloud config does not belong in it,
# and no key of any kind should be checked in there (rule 4).
goji_write_device_env() {
  local dest="$GOJI_COMPUTER_DIR/backend/.env.local-cloud"
  cat > "$dest" <<EOF
# GENERATED by goji-docs scripts/local-env.sh — do not commit, do not ship.
# Points this Goji at the local Supabase stack instead of the family project.
# The key below is the fixed Supabase local-development demo key, not a secret.
GOJI_SYNC_MODE=live
GOJI_CLOUD_URL=$SB_URL/functions/v1
GOJI_CLOUD_ANON_KEY=$SB_ANON
GOJI_SYNC_INTERVAL_S=20
GOJI_SYNC_INTERVAL_ACTIVE_S=10
GOJI_CLOUD_TIMEOUT_S=30
GOJI_DEV_API=1
EOF
  echo "$dest"
}

# A parent access token for the demo account, creating the account if needed.
goji_parent_jwt() {
  curl -fsS -X POST "$SB_URL/auth/v1/signup" \
    -H "apikey: $SB_ANON" -H 'Content-Type: application/json' \
    -d "{\"email\":\"$GOJI_TEST_EMAIL\",\"password\":\"$GOJI_TEST_PASSWORD\"}" \
    >/dev/null 2>&1 || true
  curl -fsS -X POST "$SB_URL/auth/v1/token?grant_type=password" \
    -H "apikey: $SB_ANON" -H 'Content-Type: application/json' \
    -d "{\"email\":\"$GOJI_TEST_EMAIL\",\"password\":\"$GOJI_TEST_PASSWORD\"}" \
    | python3 -c 'import sys,json; print(json.load(sys.stdin)["access_token"])'
}

# One device sync cycle, with the live-cloud env loaded.
goji_sync_once() {
  ( set -a; . "$GOJI_COMPUTER_DIR/backend/.env.local-cloud"; set +a
    cd "$GOJI_COMPUTER_DIR/backend"
    . .venv/bin/activate
    python -m sync.agent --once "$@" )
}
